[project]
site_name = "Supabase Cache Helpers"
site_description = "A collection of framework specific Cache utilities for working with Supabase."
site_author = "Philipp Steinroetter"
site_url = "https://supabase-cache-helpers.vercel.app"
repo_url = "https://github.com/psteinroe/supabase-cache-helpers"
docs_dir = "content"
site_dir = "site"

copyright = """
&copy; 2025, Philipp Steinroetter. Licensed under <a href="https://opensource.org/licenses/MIT">MIT License</a>.
"""

nav = [
  { "Introduction" = "index.md" },
  { "Configuration" = "configuration.md" },
  { "PostgREST" = [
    { "Getting Started" = "postgrest/getting-started.md" },
    { "Queries" = "postgrest/queries.md" },
    { "Mutations" = "postgrest/mutations.md" },
    { "Subscriptions" = "postgrest/subscriptions.md" },
    { "Custom Cache Updates" = "postgrest/custom-cache-updates.md" },
    { "Server-Side Rendering" = [
      { "SWR" = "postgrest/ssr/swr.md" },
      { "React Query" = "postgrest/ssr/react-query.md" },
    ]},
    { "Server-Side Caching" = "postgrest/server.md" },
  ]},
  { "Storage" = [
    { "Getting Started" = "storage/getting-started.md" },
    { "Queries" = "storage/queries.md" },
    { "Mutations" = "storage/mutations.md" },
  ]},
]

[project.theme]
language = "en"

[project.theme.icon]
logo = "fontawesome/solid/handshake"
repo = "fontawesome/brands/github"

features = [
    "announce.dismiss",
    "content.code.annotate",
    "content.code.copy",
    "content.code.select",
    "content.footnote.tooltips",
    "content.tabs.link",
    "content.tooltips",
    "navigation.footer",
    "navigation.indexes",
    "navigation.instant",
    "navigation.instant.prefetch",
    "navigation.path",
    "navigation.sections",
    "navigation.top",
    "navigation.tracking",
    "search.highlight",
]

[[project.theme.palette]]
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to light mode"

[[project.extra.social]]
icon = "fontawesome/brands/github"
link = "https://github.com/psteinroe/supabase-cache-helpers"

[[project.extra.social]]
icon = "fontawesome/brands/twitter"
link = "https://twitter.com/psteinroe"

[markdown_extensions]
admonition = {}
"pymdownx.details" = {}
"pymdownx.superfences" = {}
"pymdownx.tabbed" = { alternate_style = true }
"pymdownx.highlight" = { use_pygments = true }
